version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm run test
  build:
    commands:
      - npm run deploy:cicd #deploys to a cicd env     
  post_build:
    commands:
      #here we have to deploy to corresponging stage if staging we need to run some integration tests
      #- npm run test:remote #run test invoking the lambda functions in the cicd env (integration tests)
      # TODO: implement and run end to end tests.