version: 0.1

phases:
  install:
    commands:
      - echo $SHELL
      - printenv
      - chmod 700 $CODEBUILD_SRC_DIR/build/0.env.sh
      - head -50 $CODEBUILD_SRC_DIR/build/0.env.sh
      - echo
      - node --version
      - npm --version
  pre_build:
    commands:
      - chmod 700 $CODEBUILD_SRC_DIR/build/1.install.sh
      - head -50 $CODEBUILD_SRC_DIR/build/1.install.sh
      - npm run root:install       # Root Project (Dev Dependencies)
  build:
    commands:
      - npm run test
      - npm run lint
      - chmod 700 $CODEBUILD_SRC_DIR/build/2.sls.sh
      - head -50 $CODEBUILD_SRC_DIR/build/2.sls.sh
      - npm run root:deploy:all:cicd
      #TODO run integration and end to end example